server.port=8081    
spring.application.name=Inventario   

# 1. Configuración de la URL (Usa la de tu consola de Oracle)
# Si no usas Wallet aún, se ve así:
spring.datasource.url=jdbc:oracle:thin:@basededatosbupa_high?TNS_ADMIN=D:/FULLSTACK/Proyecto_BUPA/Wallet

# 2. Credenciales (Las que pusiste al crear la DB en la nube)
spring.datasource.username=INVENTARIO
spring.datasource.password=Duocuc12345.

# 3. Driver y Dialecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 4. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000